[WIP][MIG] account_multicurrency_revaluation: Migration to 12.0
Vauxoo/account-closing pull request #2
Opened 2018-11-27 11:36 UTC by goliveirab

2018-11-28 02:13 UTC, hbto commented
https://github.com/Vauxoo/account-closing/blob/11.0/oca_dependencies.txt

Branch for account-financial-tools (dev branch) must be included in here so that runbot instance in oca can be properly built.

@goliveirab

2018-11-28 03:40 UTC, hbto requested changes

2018-11-28 03:40 UTC, hbto commented on oca_dependencies.txt
> +account-closing
This needs to point towards https://github.com/vauxoo-dev/account-financial-tools/commits/12.0-account_reversal-hbto

in order it to work properly as in https://git.vauxoo.com/vauxoo/enterprise-mx/merge_requests/468/diffs#03a80bdbacce644481ba04cd71187eab200677f9_3_4

and this CI can run smoothly
https://runbot.odoo-community.org/runbot/repo/github-com-oca-account-closing-89 on your PR.

Regards

2018-12-26 21:29 UTC, hbto commented on account_multicurrency_revaluation/model/account.py
> +                    "account.data_account_type_payable").id else False
@goliveirab  

Save 

`
rec_pay = [self.env.ref("account.data_account_type_receivable").id, self.env.ref("account.data_account_type_payable").id]
`

in a variable outside the scope of the for loop thus saving cpu cycles.
and than make a make a comparison like:

`receive_pay = True if account_type.id  in rec_pay` else False

2018-12-27 17:41 UTC, goliveirab commented on account_multicurrency_revaluation/model/account.py
> +                    "account.data_account_type_payable").id else False
@hbto 

Is this what you expect? https://github.com/Vauxoo/account-closing/pull/2/commits/560c5c4abcd24dc59b39a8cd6e33dd743f49e0f5

2018-12-27 19:37 UTC, hbto commented
yes it is
Quien suscribe,

*Hbto*



On Thu, Dec 27, 2018 at 11:41 AM Germana Oliveira <notifications@github.com>
wrote:

> *@goliveirab* commented on this pull request.
> ------------------------------
>
> In account_multicurrency_revaluation/model/account.py
> <https://github.com/Vauxoo/account-closing/pull/2#discussion_r244196375>:
>
> >              accounts.setdefault(account_id, {})
> -            accounts[account_id].setdefault(currency_id, {})
> -            accounts[account_id][currency_id].\
> -                setdefault(partner_id, {})
> -            accounts[account_id][currency_id][partner_id] = line
> +            receive_pay = True if account_type.id == \
> +                self.env.ref("account.data_account_type_receivable").id or \
> +                account_type.id == self.env.ref(
> +                    "account.data_account_type_payable").id else False
>
> @hbto <https://github.com/hbto>
>
> Is this what you expect? 560c5c4
> <https://github.com/Vauxoo/account-closing/commit/560c5c4abcd24dc59b39a8cd6e33dd743f49e0f5>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Vauxoo/account-closing/pull/2#discussion_r244196375>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHPvur5OZO_A8NMsBwMBCBlvUBpIzL0bks5u9QZCgaJpZM4Y1TWY>
> .
>

2020-09-06 06:01 UTC, merged